apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    type: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: test-deployment
  template:
    metadata:
      labels:
        type: test-deployment
    spec:
      containers:
      - image: piotrzan/nginx-demo:green
        name: nginx-test
        volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: false
      volumes:
      - name: foo
        configMap:
          name: config-demo