apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  template:
    spec:
      containers:
      - name: nginx-test
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 150m
            memory: 128Mi