apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-secret
  labels:
    type: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: test-deployment-secret
  template:
    metadata:
      labels:
        type: test-deployment-secret
    spec:
      containers:
      - image: piotrzan/nginx-demo:green
        name: nginx-test
        volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: foo
        secret:
          secretName: mysecret-encoded